// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecretSanta.Core.Domain.Contexts;

namespace SecretSanta.Core.Migrations
{
    [DbContext(typeof(SantaContext))]
    [Migration("20220130014800_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("SecretSanta.Core.Domain.Peeps", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("BeenPicked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("PictureLocation")
                        .HasColumnType("text");

                    b.Property<bool>("ToPick")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UniquePassword")
                        .HasColumnType("text");

                    b.Property<bool>("WhatNo")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("ID");

                    b.ToTable("Peeps");
                });

            modelBuilder.Entity("SecretSanta.Core.Domain.whopickedwho", b =>
                {
                    b.Property<int>("Person1")
                        .HasColumnType("int");

                    b.Property<int>("Person2")
                        .HasColumnType("int");

                    b.HasKey("Person1", "Person2");

                    b.ToTable("whopickedwho");
                });
#pragma warning restore 612, 618
        }
    }
}
